title: Ezgi Erolsun
theme: jekyll-theme-midnight
#logo: /assets/loop.png
#show_downloads:true
description: "This page is my home page and shows basic things like my projects, process, codes and ideas"
